# Generated by Django 4.2.2 on 2023-07-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editdistance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditDistanceWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_one', models.CharField(max_length=60)),
                ('word_two', models.CharField(max_length=60)),
                ('word_one_calc', models.CharField(default='', max_length=60)),
                ('word_two_calc', models.CharField(default='', max_length=60)),
                ('distance', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Words',
        ),
    ]
